<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="simple_rover">
  <xacro:property name="wheel_separation" value="0.070" />
  <xacro:property name="wheel_radius" value="0.3" />
  <xacro:property name="caster_wheel_radius" value="0.2" />
  <xacro:property name="wheel_width" value="0.25" />
  <xacro:property name="body_height" value="0.3" />
  <xacro:property name="body_width" value="0.5" />
  <xacro:property name="body_length" value="1.0" />

  <gazebo reference="base_link">
    <material>Gazebo/White</material>
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
  </gazebo>

  <gazebo reference="right_wheel">
    <material>Gazebo/Red</material>
    <mu1>0.84</mu1>
    <mu2>0.84</mu2>
  </gazebo>

  <gazebo reference="left_wheel">
    <material>Gazebo/Red</material>
    <mu1>0.84</mu1>
    <mu2>0.84</mu2>
  </gazebo>

  <gazebo reference="caster_wheel">
    <material>Gazebo/Black</material>
    <mu1>0.84</mu1>
    <mu2>0.84</mu2>
  </gazebo>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="1"/>
      <inertia ixx="0.166667" ixy="0" ixz="0" iyy="0.166667" iyz="0" izz="0.166667"/>
    </inertial>
  </link>

  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="1"/>
      <inertia ixx="0.145833" ixy="0.0" ixz="0.0" iyy="0.145833" iyz="0.0" izz="0.125"/>
    </inertial>
  </link>

  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="1"/>
      <inertia ixx="0.145833" ixy="0.0" ixz="0.0" iyy="0.145833" iyz="0.0" izz="0.125"/>
    </inertial>
  </link>

  <link name="caster_wheel">
    <visual>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
        <sphere radius="${caster_wheel_radius}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="1"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
  </link>

  <joint name="joint_left" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <axis xyz="0 0 1"/>
    <origin xyz="${body_width/2} ${body_width/2 + wheel_width/2} 0" rpy="-${pi/2} 0 0" />
    <dynamics friction="0.1"/>
  </joint>

  <joint name="joint_right" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <axis xyz="0 0 1"/>
    <origin xyz="${body_width/2} -${body_width/2 + wheel_width/2} 0" rpy="-${pi/2} 0 0" />
    <dynamics friction="0.1"/>
  </joint>

  <joint name="joint_caster_wheel" type="continuous">
    <parent link="base_link"/>
    <child link="caster_wheel"/>
    <axis xyz="0 0 1"/>
    <origin xyz="-${body_width/2} 0 ${caster_wheel_radius - wheel_radius}" rpy="${pi/2} 0 0"/>
    <dynamics friction="0.1"/>
  </joint>

  <gazebo>
    <plugin name="simple_rover_diff_drive" filename="libgazebo_ros_diff_drive.so">
      <update_rate>30</update_rate>

      <!-- wheels -->
      <left_joint>joint_left</left_joint>
      <right_joint>joint_right</right_joint>

      <!-- kinematics -->
      <wheel_separation>0.52</wheel_separation>
      <wheel_diameter>0.28</wheel_diameter>

      <!-- limits -->
      <max_wheel_torque>20</max_wheel_torque>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>

      <!-- Receive velocity commands on this ROS topic -->
      <command_topic>cmd_vel</command_topic>
    </plugin>
  </gazebo>


</robot>